"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import type { ProjectRegistryItem } from "@/lib/types";
import ProjectWorkspace from "@/components/ProjectWorkspace";
import { MonthlyHistory, PortfolioCommandCenter, PortfolioQuality, ProjectCards } from "@/components/PortfolioWorkspace";
import { money } from "@/lib/normalized";
import OutputStudio from "@/components/OutputStudio";

type Tab="portfolio"|"projects"|"monthly"|"quality"|"sources"|"output"|"system";
const NAV:{id:Tab;label:string}[]=[{id:"portfolio",label:"Portfolio Command Center"},{id:"projects",label:"Projects"},{id:"monthly",label:"Monthly Intelligence"},{id:"quality",label:"Data Quality"},{id:"sources",label:"Sources"},{id:"output",label:"Output Studio"},{id:"system",label:"System"}];

function SystemPanel({portfolio}:{portfolio:any}){return <div className="grid2"><div className="card"><h3>Automation Contract</h3><ol className="flow"><li>Detect new/changed XLSX in INPUT</li><li>Wait for file stability and calculate SHA-256</li><li>Discover project, reporting period and workbook structure</li><li>Parse every visible and hidden sheet</li><li>Detect table regions, formulas and Excel chart definitions</li><li>Generate project-isolated data and immutable period/revision history</li><li>Run completeness, isolation and no-hardcode gates</li><li>Run Next.js production build</li><li>Commit controlled generated outputs</li><li>Push GitHub main → Vercel deployment</li><li>Verify live registry fingerprint</li></ol></div><div className="card"><h3>Current Generated Registry</h3><dl><dt>Projects</dt><dd>{portfolio?.project_count??0}</dd><dt>Generated</dt><dd>{portfolio?.generated_at??"—"}</dd><dt>Registry fingerprint</dt><dd className="mono">{portfolio?.registry_fingerprint??"—"}</dd></dl><p className="sub">A failed or ambiguous workbook never replaces a last validated version. Cross-project contamination is a deployment-blocking failure.</p></div></div>}

function SourceRegistry({projects,onOpen}:{projects:ProjectRegistryItem[];onOpen:(id:string)=>void}){return <div className="card"><h3>Source Registry</h3><p className="sub">Every project source is isolated by permanent project ID, reporting period and source SHA-256.</p><div className="tablewrap"><table><thead><tr><th>Project</th><th>Period</th><th>Fingerprint</th><th>Sheets</th><th>Excel Charts</th><th>Capabilities</th><th>Current AC</th></tr></thead><tbody>{projects.map(p=><tr key={p.project_id} className="clickable-row" onClick={()=>onOpen(p.project_id)}><td className="pname">{p.project_name}</td><td>{p.reporting_period}</td><td className="mono">{p.source_fingerprint}</td><td>{p.sheet_count}</td><td>{p.chart_count}</td><td>{Object.entries(p.capabilities||{}).filter(([,v])=>v).map(([k])=>k.replaceAll("_"," ")).join(" · ")}</td><td>{money(p.metrics?.actual_cost)}</td></tr>)}</tbody></table></div></div>}

function OlaOverlay(){const [show,setShow]=useState(false);const seq=useRef(0);const hold=useRef<ReturnType<typeof setTimeout>|null>(null);useEffect(()=>{const key=(e:KeyboardEvent)=>{const expected=String(seq.current+1);if(e.key===expected){seq.current++;if(seq.current===5){setShow(true);seq.current=0}}else seq.current=e.key==="1"?1:0};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[]);const start=()=>{if(hold.current)clearTimeout(hold.current);hold.current=setTimeout(()=>setShow(true),3000)};const end=()=>{if(hold.current)clearTimeout(hold.current);hold.current=null};return <><div className={`olaHotspot ${show?"active":""}`} onPointerDown={start} onPointerUp={end} onPointerCancel={end} onPointerLeave={end} title=""></div><div id="olaOverlay" className={show?"show":""} onClick={()=>setShow(false)}><div className="msg">Eng. Ola — CTO Cost Intelligence is live.<small>Tap anywhere to return to the command center.</small></div></div></>}

export default function Dashboard({initialProjectId}:{initialProjectId?:string}){
 const [projects,setProjects]=useState<ProjectRegistryItem[]>([]),[portfolio,setPortfolio]=useState<any>(null),[tab,setTab]=useState<Tab>("portfolio"),[projectId,setProjectId]=useState(initialProjectId||""),[clock,setClock]=useState("");
 useEffect(()=>{Promise.all([fetch("/generated/projects.json").then(r=>r.json()),fetch("/generated/portfolio/latest.json").then(r=>r.json())]).then(([p,po])=>{setProjects(p);setPortfolio(po)}).catch(()=>{})},[]);
 useEffect(()=>{const t=()=>setClock(new Intl.DateTimeFormat("en-GB",{timeZone:"Africa/Cairo",hour:"2-digit",minute:"2-digit",day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date()));t();const id=setInterval(t,30000);return()=>clearInterval(id)},[]);
 useEffect(()=>{const pop=()=>{const m=location.pathname.match(/^\/project\/([^/]+)/);setProjectId(m?decodeURIComponent(m[1]):"")};window.addEventListener("popstate",pop);return()=>window.removeEventListener("popstate",pop)},[]);
 const open=(id:string)=>{setProjectId(id);history.pushState({},"",`/project/${encodeURIComponent(id)}`);window.scrollTo({top:0,behavior:"smooth"})};const back=()=>{setProjectId("");history.pushState({},"","/");setTab("portfolio");window.scrollTo({top:0,behavior:"smooth"})};
 if(projectId)return <main className="shell"><OlaOverlay/><ProjectWorkspace projectId={projectId} onBack={back}/></main>;
 return <main className="shell"><OlaOverlay/><header className="top"><div className="brandrow"><div><div className="title">CTO <em>Cost Intelligence</em> Command Center</div><div className="subtitle">Technical Director · Adaptive Workbook Intelligence · Cairo {clock}</div></div><div className="approval">NO HARD-CODED PROJECTS · STRICT PROJECT ISOLATION</div></div><nav className="nav">{NAV.map(n=><button key={n.id} className={tab===n.id?"active":""} onClick={()=>setTab(n.id)}>{n.label}</button>)}</nav></header>{tab==="portfolio"&&<PortfolioCommandCenter projects={projects} onOpen={open}/>} {tab==="projects"&&<ProjectCards projects={projects} onOpen={open}/>} {tab==="monthly"&&<MonthlyHistory projects={projects}/>} {tab==="quality"&&<PortfolioQuality projects={projects} onOpen={open}/>} {tab==="sources"&&<SourceRegistry projects={projects} onOpen={open}/>} {tab==="output"&&<OutputStudio projects={projects}/>} {tab==="system"&&<SystemPanel portfolio={portfolio}/>}</main>;
}
