"use client";

import { useEffect, useMemo, useState } from "react";
import type { NormalizedData, PortfolioModel, ProjectRegistryItem } from "@/lib/types";
import { money, pct, portfolioBase, scoped } from "@/lib/normalized";
import { BubbleChart, ChartShell, GroupedBarChart, LineChart } from "@/components/Charts";

type Scope="dashboard"|"total";
type Display="bars"|"index"|"share";
type MonthMetric="cash_in"|"cash_out"|"net"|"cash_in_cum"|"cash_out_cum"|"net_cum";

function Kpi({label,value,note}:{label:string;value:string;note?:string}){return <div className="kpi"><span>{label}</span><b>{value}</b>{note&&<small>{note}</small>}</div>}

export function usePortfolioModels(projects:ProjectRegistryItem[]) {
 const [norms,setNorms]=useState<Record<string,NormalizedData|null>>({});
 useEffect(()=>{let dead=false;Promise.all(projects.map(async p=>{if(!p.normalized_path)return [p.project_id,null] as const;try{const r=await fetch(p.normalized_path);return [p.project_id,r.ok?await r.json():null] as const}catch{return [p.project_id,null] as const}})).then(items=>{if(!dead)setNorms(Object.fromEntries(items))});return()=>{dead=true}},[projects]);
 return projects.map(registry=>({registry,normalized:norms[registry.project_id]??null}));
}

function Controls({models,selected,setSelected,scope,setScope}:{models:PortfolioModel[];selected:Set<string>;setSelected:(s:Set<string>)=>void;scope:Scope;setScope:(s:Scope)=>void}){
 const toggle=(id:string)=>{const n=new Set(selected);if(n.has(id)){if(n.size>1)n.delete(id)}else n.add(id);setSelected(n)};
 return <div className="hero"><div className="card"><h3>Portfolio control deck <span className="new">NEW</span></h3><p className="sub">Choose projects and cost scope. Every comparison below updates together; source values are never overwritten.</p><div className="chips">{models.map(m=><button type="button" className={`chip ${selected.has(m.registry.project_id)?"on":""}`} key={m.registry.project_id} onClick={()=>toggle(m.registry.project_id)}>{m.registry.project_name}</button>)}</div></div><div className="card"><h3>Executive comparison rules</h3><p className="sub">Operational Dashboard Scope uses headline dashboard figures. Full Project Summary Cost Scope uses the wider project-summary totals where available. The two scopes stay separate so unlike totals are never mixed.</p><div className="controls"><select value={scope} onChange={e=>setScope(e.target.value as Scope)}><option value="dashboard">Operational Dashboard Scope</option><option value="total">Full Project Summary Cost Scope</option></select></div><p className="source-tag">Scope changes only the comparable EV/Actual Cost basis; it does not change or overwrite source data.</p></div></div>;
}

function CostMatrix({rows,onOpen}:{rows:any[];onOpen:(id:string)=>void}){
 const metrics:any={contract:["Contract Price",(p:any)=>p.contract],budget:["Budget",(p:any)=>p.budget],ev:["Earned Value",(p:any)=>p.ev],ac:["Actual Cost",(p:any)=>p.ac],cv:["Cost Variance",(p:any)=>p.cv],cpi:["CPI",(p:any)=>p.cpi],gp_pct:["Gross Profit %",(p:any)=>p.gpPct*100],indirect_var:["Indirect Budget Variance",(p:any)=>p.indirectVar]};
 const [metric,setMetric]=useState("ac"),[display,setDisplay]=useState<Display>("bars"),[sort,setSort]=useState("ac"),[dir,setDir]=useState(-1);const fn=metrics[metric][1];const sorted=[...rows].sort((a,b)=>{const av=sort==="name"?a.name:(a[sort]??0),bv=sort==="name"?b.name:(b[sort]??0);return typeof av==="string"?av.localeCompare(bv)*dir:((+av||0)-(+bv||0))*dir});const vals=rows.map(fn).filter((v:any)=>v!=null&&Number.isFinite(+v)).map(Number),max=Math.max(1,...vals.map(Math.abs)),sum=Math.max(1,vals.reduce((a:number,v:number)=>a+Math.abs(v),0));const hi=rows.length?rows.reduce((a,b)=>(+fn(b)||0)>(+fn(a)||0)?b:a):null,lo=rows.length?rows.reduce((a,b)=>(+fn(b)||0)<(+fn(a)||0)?b:a):null,gap=hi&&lo?(+fn(hi)||0)-(+fn(lo)||0):0,ratio=hi&&lo&&Math.abs(+fn(lo)||0)>1e-9?Math.abs((+fn(hi)||0)/(+fn(lo)||0)):null;
 const format=(v:number)=>metric==="cpi"?v.toFixed(2):metric==="gp_pct"?`${v.toFixed(1)}%`:money(v);
 return <div className="card"><h3>CTO Technical Cost Matrix <span className="new">NEW</span></h3><p className="sub">Executive peer-comparison matrix. Sort any column, change the analysis metric and display mode, inspect the peer gap, then tap a project row to open its full SAP dashboard.</p><div className="matrixTools"><div className="toolgroup"><label>Analysis metric</label><select value={metric} onChange={e=>setMetric(e.target.value)}>{Object.entries(metrics).map(([k,v]:any)=><option value={k} key={k}>{v[0]}</option>)}</select></div><div className="toolgroup"><label>In-table chart</label><select value={display} onChange={e=>setDisplay(e.target.value as Display)}><option value="bars">Value bars</option><option value="index">Peer index</option><option value="share">Portfolio share</option></select></div></div><div className="matrixSummary"><div className="micro"><span>Selected metric</span><b>{metrics[metric][0]}</b></div><div className="micro"><span>Highest reported value</span><b>{hi?`${hi.name} · ${format(fn(hi))}`:"—"}</b></div><div className="micro"><span>Peer difference</span><b>{rows.length>1?format(gap):"—"}</b></div><div className="micro"><span>High / low ratio</span><b>{ratio!=null&&Number.isFinite(ratio)?`${ratio.toFixed(2)}×`:"—"}</b></div></div><div className="tablewrap"><table><thead><tr>{[["name","Project"],["contract","Contract Price"],["budget","Budget"],["ev","EV"],["ac","AC"],["cv","CV"],["cpi","CPI"],["directAc","Direct AC"],["indirectAc","Indirect AC"],["revenue","Revenue"],["gp","Gross Profit"],["gpPct","GP %"],["indirectVar","Indirect Budget Var."]].map(([k,l])=><th key={k} onClick={()=>{if(sort===k)setDir(-dir);else{setSort(k);setDir(-1)}}}>{l}</th>)}<th>{metrics[metric][0]} comparison</th></tr></thead><tbody>{sorted.map((p,i)=>{const v=+fn(p)||0,bar=display==="share"?Math.abs(v)/sum*100:Math.abs(v)/max*100,label=display==="index"?`${bar.toFixed(0)} index`:display==="share"?`${bar.toFixed(1)}% share`:format(v);return <tr key={p.id} className="clickable-row" onClick={()=>onOpen(p.id)}><td className="pname"><span className="matrixRank">{i+1}</span>{p.name}</td><td>{money(p.contract)}</td><td>{money(p.budget)}</td><td>{money(p.ev)}</td><td>{money(p.ac)}</td><td className={p.cv>=0?"pos":"neg"}>{money(p.cv)}</td><td>{p.cpi?.toFixed(2)??"—"}</td><td>{money(p.directAc)}</td><td>{money(p.indirectAc)}</td><td>{money(p.revenue)}</td><td className={p.gp>=0?"pos":"neg"}>{money(p.gp)}</td><td className={p.gpPct>=0?"pos":"neg"}>{pct(p.gpPct,true)}</td><td className={p.indirectVar>=0?"pos":"neg"}>{money(p.indirectVar)}</td><td className="barcell">{label}<div className="bar"><i style={{width:`${Math.min(100,bar)}%`}}/></div></td></tr>})}</tbody></table></div></div>;
}

function MonthlyComparison({rows}:{rows:any[]}){
 const defs:any={cash_in:["Cash In",false,(x:any)=>x.cash_in],cash_out:["Cash Out",false,(x:any)=>x.cash_out],net:["Net Cash",false,(x:any)=>(x.cash_in||0)-(x.cash_out||0)],cash_in_cum:["Cumulative Cash In",true,(x:any)=>x.cash_in_cum],cash_out_cum:["Cumulative Cash Out",true,(x:any)=>x.cash_out_cum],net_cum:["Cumulative Net Cash",true,(x:any)=>(x.cash_in_cum||0)-(x.cash_out_cum||0)]};const [metric,setMetric]=useState<MonthMetric>("cash_in"),[coverage,setCoverage]=useState<"common"|"all">("common"),[focus,setFocus]=useState("ALL");
 const sets=rows.map(p=>new Set(p.cashflow.map((x:any)=>x.month))),months=rows.length?(coverage==="common"?[...sets[0]].filter(m=>sets.every(s=>s.has(m))):[...new Set(rows.flatMap(p=>p.cashflow.map((x:any)=>x.month)))].sort()):[];const shown=focus==="ALL"?months:months.filter(m=>m===focus),get=(p:any,m:string)=>{const x=p.cashflow.find((z:any)=>z.month===m);return x?defs[metric][2](x):null},series=rows.map(p=>({label:p.name,values:shown.map(m=>get(p,m))})),common=rows.length?[...sets[0]].filter(m=>sets.every(s=>s.has(m))).length:0,allVals=shown.flatMap(m=>rows.map(p=>get(p,m))).filter(v=>v!=null).map((v:any)=>Math.abs(v)),vmax=Math.max(1,...allVals);
 useEffect(()=>{if(focus!=="ALL"&&!months.includes(focus))setFocus("ALL")},[coverage,metric,rows.length]);
 return <div className="card"><h3>CTO Monthly Cost Comparison <span className="new">NEW</span></h3><p className="sub">Compares SAP cost reports month by month. Use common-month coverage for like-for-like review, or all source months to see each project’s full reporting history.</p><div className="matrixTools"><div className="toolgroup"><label>Monthly metric</label><select value={metric} onChange={e=>setMetric(e.target.value as MonthMetric)}>{Object.entries(defs).map(([k,v]:any)=><option value={k} key={k}>{v[0]}</option>)}</select></div><div className="toolgroup"><label>Coverage</label><select value={coverage} onChange={e=>setCoverage(e.target.value as any)}><option value="common">Common months only</option><option value="all">All source months</option></select></div><div className="toolgroup"><label>Focus</label><select value={focus} onChange={e=>setFocus(e.target.value)}><option value="ALL">All months</option>{months.map(m=><option key={m}>{m}</option>)}</select></div></div><div className="monthSummary"><div className="micro"><span>Displayed coverage</span><b>{coverage==="common"?"Common months":"All source months"} · {months.length}</b></div><div className="micro"><span>Common comparable months</span><b>{common}</b></div><div className="micro"><span>Latest comparable month</span><b>{months.at(-1)||"—"}</b></div><div className="micro"><span>Metric</span><b>{defs[metric][0]}</b></div></div><div className="monthGrid"><div className="monthChartBox">{defs[metric][1]?<LineChart labels={shown} series={series}/>:<GroupedBarChart labels={shown} series={series}/>}</div><div className="monthTableBox"><div className="tablewrap"><table id="monthlyMatrix"><thead><tr><th>Month</th>{rows.map(p=><th key={p.id}>{p.name}</th>)}{rows.length===2&&<><th>{rows[0].name} − {rows[1].name}</th><th>Higher value</th></>}</tr></thead><tbody>{shown.map(m=>{const vv=rows.map(p=>get(p,m));const diff=rows.length===2&&vv[0]!=null&&vv[1]!=null?(vv[0] as number)-(vv[1] as number):null,higher=diff==null?"—":Math.abs(diff)<1e-9?"Equal":diff>0?rows[0].name:rows[1].name;return <tr key={m} className={focus!=="ALL"?"monthFocus":""}><td className="pname">{m}</td>{vv.map((v,i)=><td key={i} className="monthCell">{v==null?<span className="muted">—</span>:<>{money(v as number)}<div className="monthBar"><i style={{width:`${Math.min(100,Math.abs(v as number)/vmax*100)}%`}}/></div></>}</td>)}{rows.length===2&&<><td className={diff==null?"muted":diff>=0?"deltaUp":"deltaDown"}>{diff==null?"—":money(diff)}</td><td>{higher==="—"?<span className="muted">—</span>:<span className="peerTag">{higher}</span>}</td></>}</tr>})}</tbody></table></div></div></div></div>;
}

function ScenarioLab({rows}:{rows:any[]}){const [who,setWho]=useState("ALL"),[cost,setCost]=useState(0),[rev,setRev]=useState(100),[ind,setInd]=useState(0);const base=who==="ALL"?rows:rows.filter(p=>p.id===who);let ac=0,eac=0,revenue=0;base.forEach(p=>{const rem=Math.max(0,p.budget-p.ev);ac+=p.ac;eac+=p.ac+rem*(1+cost/100)+p.indirectAc*(ind/100);revenue+=p.price*(rev/100)});const profit=revenue-eac,margin=revenue?profit/revenue:0;const reset=()=>{setCost(0);setRev(100);setInd(0)};return <div className="card"><h3>CTO Cost Scenario Lab <span className="new">NEW</span></h3><p className="sub">A reversible what-if model only. It does not alter SAP values. Adjust remaining-cost stress, revenue realization and indirect-cost stress to test sensitivity.</p><div className="controls"><select value={who} onChange={e=>setWho(e.target.value)}><option value="ALL">Selected Portfolio</option>{rows.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><button className="ctrl" onClick={reset}>Reset</button><span className="scenarioFlag">SCENARIO — NOT SOURCE DATA</span></div><div className="scenario"><Range label="Remaining cost stress" value={cost} set={setCost} min={-20} max={50}/><Range label="Revenue realization" value={rev} set={setRev} min={50} max={120}/><Range label="Indirect cost stress" value={ind} set={setInd} min={-20} max={60}/></div><div className="scenarioOut"><div><span>Current AC</span><b>{money(ac)}</b></div><div><span>Scenario EAC</span><b>{money(eac)}</b></div><div><span>Scenario Revenue</span><b>{money(revenue)}</b></div><div><span>Scenario Margin</span><b className={margin>=0?"pos":"neg"}>{pct(margin,true)}</b></div></div><GroupedBarChart labels={["Current AC","Scenario EAC","Scenario Revenue","Scenario Profit"]} series={[{label:"Scenario",values:[ac,eac,revenue,profit]}]}/></div>}
function Range({label,value,set,min,max}:{label:string;value:number;set:(v:number)=>void;min:number;max:number}){return <div className="rangebox"><label><span>{label}</span><b>{value}%</b></label><input type="range" min={min} max={max} value={value} onChange={e=>set(Number(e.target.value))}/></div>}

export function PortfolioCommandCenter({projects,onOpen}:{projects:ProjectRegistryItem[];onOpen:(id:string)=>void}){
 const models=usePortfolioModels(projects);const [scope,setScope]=useState<Scope>("dashboard"),[selected,setSelected]=useState<Set<string>>(()=>new Set(projects.map(p=>p.project_id))),[portfolioTab,setPortfolioTab]=useState<"charts"|"analysis">("charts");useEffect(()=>{setSelected(s=>{const valid=new Set([...s].filter(id=>projects.some(p=>p.project_id===id)));if(!valid.size)projects.forEach(p=>valid.add(p.project_id));projects.forEach(p=>{if(!s.size)valid.add(p.project_id)});return valid})},[projects.map(p=>p.project_id).join("|")]);const active=models.filter(m=>selected.has(m.registry.project_id)).map(portfolioBase).map(p=>scoped(p,scope));const sum=(k:string)=>active.reduce((a,p)=>a+(Number((p as any)[k])||0),0),ev=sum("ev"),ac=sum("ac"),gp=sum("gp"),revenue=sum("revenue"),indirectVar=sum("indirectVar");
 const marginPoints=active.map(p=>({label:p.name,x:p.cpi||0,y:p.gpPct*100,size:p.contract,detail:`${p.name} · CPI ${p.cpi?.toFixed(2)??"—"} · GP ${pct(p.gpPct,true)} · Contract ${money(p.contract)}`}));
 const months=[...new Set(active.flatMap(p=>p.cashflow.map((x:any)=>x.month)))].sort();
 return <>
  <Controls models={models} selected={selected} setSelected={setSelected} scope={scope} setScope={setScope}/>
  <div className="kpis"><Kpi label="Selected Projects" value={String(active.length)}/><Kpi label="Contract Price" value={money(sum("contract"))} note="Portfolio sum"/><Kpi label="Budget" value={money(sum("budget"))} note="Portfolio sum"/><Kpi label="Earned Value" value={money(ev)} note={scope==="dashboard"?"Operational Dashboard Scope":"Full Project Summary Cost Scope"}/><Kpi label="Actual Cost" value={money(ac)} note={scope==="dashboard"?"Operational Dashboard Scope":"Full Project Summary Cost Scope"}/><Kpi label="Portfolio CPI" value={ac?(ev/ac).toFixed(2):"—"} note={ev>=ac?"Cost efficient":"Cost pressure"}/><Kpi label="Cost Variance" value={money(ev-ac)} note={ev-ac>=0?"Favorable":"Unfavorable"}/><Kpi label="Revenue" value={money(revenue)} note="Revenue-based GP source"/><Kpi label="Gross Profit" value={money(gp)} note={revenue?pct(gp/revenue):"—"}/><Kpi label="Indirect Variance" value={money(indirectVar)} note={indirectVar>=0?"Within budget":"Over budget"}/></div>
  <nav className="portfolioTabNav" aria-label="Portfolio command center views">
   <button type="button" className={portfolioTab==="charts"?"active":""} aria-pressed={portfolioTab==="charts"} onClick={()=>setPortfolioTab("charts")}><b>Charts</b><span>Portfolio visual performance</span></button>
   <button type="button" className={portfolioTab==="analysis"?"active":""} aria-pressed={portfolioTab==="analysis"} onClick={()=>setPortfolioTab("analysis")}><b>CTO Analysis</b><span>Matrix, monthly comparison and scenario lab</span></button>
  </nav>
  {portfolioTab==="charts"&&<section className="portfolioPanel" aria-label="Portfolio charts">
   <div className="grid2"><ChartShell title="Portfolio Cost Position" description="Compares Budget, Earned Value and Actual Cost on the selected common scope." badge="NEW"><GroupedBarChart labels={active.map(p=>p.name)} series={[{label:"Budget",values:active.map(p=>p.budget)},{label:"EV",values:active.map(p=>p.ev)},{label:"Actual Cost",values:active.map(p=>p.ac)}]}/></ChartShell><ChartShell title="Margin vs Cost Performance" description="X = CPI, Y = revenue-based gross profit %, bubble size = contract price. It shows cost efficiency and margin together." badge="NEW"><BubbleChart points={marginPoints}/></ChartShell></div>
   <div className="grid2"><ChartShell title="Direct vs Indirect Actual Cost" description="Shows the reported direct/indirect cost mix for each selected project." badge="NEW"><GroupedBarChart labels={active.map(p=>p.name)} series={[{label:"Direct AC",values:active.map(p=>p.directAc)},{label:"Indirect AC",values:active.map(p=>p.indirectAc)}]}/></ChartShell><ChartShell title="Revenue, Actual Cost & Gross Profit" description="Places revenue-based profitability beside current actual cost for a fast executive margin comparison." badge="NEW"><GroupedBarChart labels={active.map(p=>p.name)} series={[{label:"Revenue",values:active.map(p=>p.revenue)},{label:"Actual Cost",values:active.map(p=>p.ac)},{label:"Gross Profit",values:active.map(p=>p.gp)}]}/></ChartShell></div>
   <ChartShell title="Portfolio Cashflow Comparison" description="Cumulative cash-in and cash-out from selected cost reports. Dates remain exactly on each project’s source timeline." badge="NEW"><LineChart labels={months} series={active.flatMap(p=>[{label:`${p.name} · Cash In`,values:months.map(m=>p.cashflow.find((x:any)=>x.month===m)?.cash_in_cum??null)},{label:`${p.name} · Cash Out`,values:months.map(m=>p.cashflow.find((x:any)=>x.month===m)?.cash_out_cum??null)}])}/></ChartShell>
  </section>}
  {portfolioTab==="analysis"&&<section className="portfolioPanel portfolioAnalysis" aria-label="CTO portfolio analysis"><CostMatrix rows={active} onOpen={onOpen}/><MonthlyComparison rows={active}/><ScenarioLab rows={active}/></section>}
 </>;
}

export function ProjectCards({projects,onOpen}:{projects:ProjectRegistryItem[];onOpen:(id:string)=>void}){return <div className="projectGrid">{projects.map(p=><button className="projectCard" onClick={()=>onOpen(p.project_id)} key={p.project_id}><div className="projectTitle">{p.project_name}</div><div className="sub">Reporting {p.reporting_period}</div><div className="miniGrid"><span>CPI <b>{p.metrics?.cpi?.toFixed(2)??"—"}</b></span><span>CV <b>{money(p.metrics?.cost_variance)}</b></span><span>Sheets <b>{p.sheet_count}</b></span><span>Quality <b>{p.quality_count}</b></span></div><div className="sourceMeta"><span>{p.approved_parity?"Approved parity source":"Adaptive source"}</span><span>{p.chart_count} Excel charts</span></div></button>)}</div>}

export function PortfolioQuality({projects,onOpen}:{projects:ProjectRegistryItem[];onOpen:(id:string)=>void}){return <div className="card"><h3>Portfolio Data Quality</h3><p className="sub">Quality findings remain project-scoped; source contradictions are reported, not silently reconciled.</p><div className="tablewrap"><table><thead><tr><th>Project</th><th>Period</th><th>Findings</th><th>Sheets</th><th>Charts</th><th>Source Fingerprint</th></tr></thead><tbody>{projects.map(p=><tr key={p.project_id} className="clickable-row" onClick={()=>onOpen(p.project_id)}><td className="pname">{p.project_name}</td><td>{p.reporting_period}</td><td>{p.quality_count}</td><td>{p.sheet_count}</td><td>{p.chart_count}</td><td className="mono">{p.source_fingerprint}</td></tr>)}</tbody></table></div></div>}

export function MonthlyHistory({projects}:{projects:ProjectRegistryItem[]}){const rows=projects.flatMap(p=>(p.history||[]).map(h=>({project:p.project_name,id:p.project_id,...h})));return <div className="card"><h3>Validated Monthly / Revision History</h3><p className="sub">Every validated reporting period remains retained per project. New months appear automatically; same-month revisions remain fingerprint-addressed.</p><div className="tablewrap"><table><thead><tr><th>Project</th><th>Period</th><th>Source SHA-256</th><th>Budget</th><th>EV</th><th>AC</th><th>CV</th><th>CPI</th></tr></thead><tbody>{rows.map((r:any,i)=><tr key={`${r.id}-${r.reporting_period}-${i}`}><td className="pname">{r.project}</td><td>{r.reporting_period}</td><td className="mono">{r.source_fingerprint}</td><td>{money(r.metrics?.budget)}</td><td>{money(r.metrics?.earned_value)}</td><td>{money(r.metrics?.actual_cost)}</td><td>{money(r.metrics?.cost_variance)}</td><td>{r.metrics?.cpi?.toFixed(2)??"—"}</td></tr>)}</tbody></table></div></div>}
